// Code generated by "stringer -type=OpType -output=zstring.go"; DO NOT EDIT.

package md

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpText-0]
	_ = x[OpRawHTML-1]
	_ = x[OpThematicBreak-2]
	_ = x[OpHeadingStart-3]
	_ = x[OpHeadingEnd-4]
	_ = x[OpCodeBlockStart-5]
	_ = x[OpCodeBlockEnd-6]
	_ = x[OpParagraphStart-7]
	_ = x[OpParagraphEnd-8]
	_ = x[OpBlockquoteStart-9]
	_ = x[OpBlockquoteEnd-10]
	_ = x[OpListItemStart-11]
	_ = x[OpListItemEnd-12]
	_ = x[OpBulletListStart-13]
	_ = x[OpBulletListEnd-14]
	_ = x[OpOrderedListStart-15]
	_ = x[OpOrderedListEnd-16]
	_ = x[OpCodeSpanStart-17]
	_ = x[OpCodeSpanEnd-18]
	_ = x[OpEmphasisStart-19]
	_ = x[OpEmphasisEnd-20]
	_ = x[OpStrongEmphasisStart-21]
	_ = x[OpStrongEmphasisEnd-22]
	_ = x[OpLinkStart-23]
	_ = x[OpLinkEnd-24]
	_ = x[OpImage-25]
	_ = x[OpHardLineBreak-26]
}

const _OpType_name = "OpTextOpRawHTMLOpThematicBreakOpHeadingStartOpHeadingEndOpCodeBlockStartOpCodeBlockEndOpParagraphStartOpParagraphEndOpBlockquoteStartOpBlockquoteEndOpListItemStartOpListItemEndOpBulletListStartOpBulletListEndOpOrderedListStartOpOrderedListEndOpCodeSpanStartOpCodeSpanEndOpEmphasisStartOpEmphasisEndOpStrongEmphasisStartOpStrongEmphasisEndOpLinkStartOpLinkEndOpImageOpHardLineBreak"

var _OpType_index = [...]uint16{0, 6, 15, 30, 44, 56, 72, 86, 102, 116, 133, 148, 163, 176, 193, 208, 226, 242, 257, 270, 285, 298, 319, 338, 349, 358, 365, 380}

func (i OpType) String() string {
	if i >= OpType(len(_OpType_index)-1) {
		return "OpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpType_name[_OpType_index[i]:_OpType_index[i+1]]
}
