// Code generated by "stringer -type=OpType -output=zstring.go"; DO NOT EDIT.

package md

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpText-0]
	_ = x[OpRawHTML-1]
	_ = x[OpThematicBreak-2]
	_ = x[OpHeadingStart-3]
	_ = x[OpHeadingEnd-4]
	_ = x[OpCodeBlockStart-5]
	_ = x[OpCodeBlockEnd-6]
	_ = x[OpHTMLBlockStart-7]
	_ = x[OpHTMLBlockEnd-8]
	_ = x[OpParagraphStart-9]
	_ = x[OpParagraphEnd-10]
	_ = x[OpBlockquoteStart-11]
	_ = x[OpBlockquoteEnd-12]
	_ = x[OpListItemStart-13]
	_ = x[OpListItemEnd-14]
	_ = x[OpBulletListStart-15]
	_ = x[OpBulletListEnd-16]
	_ = x[OpOrderedListStart-17]
	_ = x[OpOrderedListEnd-18]
	_ = x[OpCodeSpanStart-19]
	_ = x[OpCodeSpanEnd-20]
	_ = x[OpEmphasisStart-21]
	_ = x[OpEmphasisEnd-22]
	_ = x[OpStrongEmphasisStart-23]
	_ = x[OpStrongEmphasisEnd-24]
	_ = x[OpLinkStart-25]
	_ = x[OpLinkEnd-26]
	_ = x[OpImage-27]
	_ = x[OpHardLineBreak-28]
}

const _OpType_name = "OpTextOpRawHTMLOpThematicBreakOpHeadingStartOpHeadingEndOpCodeBlockStartOpCodeBlockEndOpHTMLBlockStartOpHTMLBlockEndOpParagraphStartOpParagraphEndOpBlockquoteStartOpBlockquoteEndOpListItemStartOpListItemEndOpBulletListStartOpBulletListEndOpOrderedListStartOpOrderedListEndOpCodeSpanStartOpCodeSpanEndOpEmphasisStartOpEmphasisEndOpStrongEmphasisStartOpStrongEmphasisEndOpLinkStartOpLinkEndOpImageOpHardLineBreak"

var _OpType_index = [...]uint16{0, 6, 15, 30, 44, 56, 72, 86, 102, 116, 132, 146, 163, 178, 193, 206, 223, 238, 256, 272, 287, 300, 315, 328, 349, 368, 379, 388, 395, 410}

func (i OpType) String() string {
	if i >= OpType(len(_OpType_index)-1) {
		return "OpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpType_name[_OpType_index[i]:_OpType_index[i+1]]
}
