#!/bin/sh

# Outputs the extra dependencies of a doc.
#
# Must be run from the website directory.

cat ${1%.html}.md |
  awk '$1 == "@module" { if ($2 == "builtin") { print "pkg/eval" } else if ($2 == "edit") { print "pkg/edit" } else { print "pkg/mods/" $2 } }' |
  sed 's/-//g' |
  while read dir; do
    echo ../$dir ../$dir/*.elv
  done

cat ${1%.html}.md |
  awk '$1 == "@ttyshot" { print $2 ".ttyshot.html" }'
