#!/bin/sh
in=$1
out=$2
opts=

has() {
    head -n1 $in | grep "$@" >/dev/null
}

has toc && {
    opts="$opts --toc --template=toc-and-body"
}
has number-sections && {
    opts="$opts --number-sections"
}

mydir=$(dirname "$0")

$mydir/macros.bin -repo $mydir/../.. -elvdoc $mydir/elvdoc.bin < $1 |
  $mydir/highlight.bin |
  pandoc -f gfm+smart+attributes --data-dir=$mydir/pandoc-data --metadata title=${1%.md} -o $2 $opts
