#!/bin/sh
mydir=$(dirname "$0")
in=$1
out=$2
opts=

has() {
    head -n1 $in | grep "$@" >/dev/null
}

has toc && {
    opts="$opts --toc --template=toc-and-body"
}
has number-sections && {
    opts="$opts --number-sections"
}

$mydir/macros.bin -repo $mydir/../.. -elvdoc $mydir/elvdoc.bin < $in |
  $mydir/highlight.bin |
  pandoc -f gfm+smart+attributes --data-dir=$mydir/pandoc --lua-filter=$mydir/pandoc/header-anchors.lua --metadata title=${1%.md} -o $out $opts
