// Code generated by "stringer -type=PrimaryType,RedirMode,ExprCtx -output=string.go"; DO NOT EDIT.

package parse

import "strconv"

const _PrimaryType_name = "BadPrimaryBarewordSingleQuotedDoubleQuotedVariableWildcardTildeExceptionCaptureOutputCaptureListLambdaMapBraced"

var _PrimaryType_index = [...]uint8{0, 10, 18, 30, 42, 50, 58, 63, 79, 92, 96, 102, 105, 111}

func (i PrimaryType) String() string {
	if i < 0 || i >= PrimaryType(len(_PrimaryType_index)-1) {
		return "PrimaryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrimaryType_name[_PrimaryType_index[i]:_PrimaryType_index[i+1]]
}

const _RedirMode_name = "BadRedirModeReadWriteReadWriteAppend"

var _RedirMode_index = [...]uint8{0, 12, 16, 21, 30, 36}

func (i RedirMode) String() string {
	if i < 0 || i >= RedirMode(len(_RedirMode_index)-1) {
		return "RedirMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RedirMode_name[_RedirMode_index[i]:_RedirMode_index[i+1]]
}

const _ExprCtx_name = "NormalExprCmdExprLHSExprBracedElemExprstrictExpr"

var _ExprCtx_index = [...]uint8{0, 10, 17, 24, 38, 48}

func (i ExprCtx) String() string {
	if i < 0 || i >= ExprCtx(len(_ExprCtx_index)-1) {
		return "ExprCtx(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExprCtx_name[_ExprCtx_index[i]:_ExprCtx_index[i+1]]
}
