// generated by stringer -type=PrimaryType,RedirMode -output=string.go; DO NOT EDIT

package parse

import "fmt"

const _PrimaryType_name = "BadPrimaryBarewordSingleQuotedDoubleQuotedVariableWildcardTildeErrorCaptureOutputCaptureListLambdaMapBraced"

var _PrimaryType_index = [...]uint8{0, 10, 18, 30, 42, 50, 58, 63, 75, 88, 92, 98, 101, 107}

func (i PrimaryType) String() string {
	if i < 0 || i+1 >= PrimaryType(len(_PrimaryType_index)) {
		return fmt.Sprintf("PrimaryType(%d)", i)
	}
	return _PrimaryType_name[_PrimaryType_index[i]:_PrimaryType_index[i+1]]
}

const _RedirMode_name = "BadRedirModeReadWriteReadWriteAppend"

var _RedirMode_index = [...]uint8{0, 12, 16, 21, 30, 36}

func (i RedirMode) String() string {
	if i < 0 || i+1 >= RedirMode(len(_RedirMode_index)) {
		return fmt.Sprintf("RedirMode(%d)", i)
	}
	return _RedirMode_name[_RedirMode_index[i]:_RedirMode_index[i+1]]
}
