test_task:
  env:
    ELVISH_TEST_TIME_SCALE: 20
  go_modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  matrix:
    - name: Test on Linux (Gccgo)
      container:
        image: debian:unstable-slim
      setup_script:
        - apt-get -y update
        - apt-get -y install ca-certificates gccgo-go
      env:
        # Gccgo doesn't support race test
        TEST_FLAG: ""
    - name: Test on FreeBSD
      freebsd_instance:
        image_family: freebsd-12-1
      setup_script: pkg install -y go
      env:
        GOPATH: $HOME/go
        TEST_FLAG: -race
  go_version_script: go version
  test_script: go test $TEST_FLAG ./...

checkstyle_go_task:
  name: Check the style of .go files
  container:
    image: golang:latest
  env:
    PATH: $HOME/go/bin:$PATH
  setup_script: go get golang.org/x/tools/cmd/goimports
  check_script: make checkstyle-go

checkstyle_md_task:
  name: Check the style of .md files
  container:
    image: node:latest
  env:
    PATH: $HOME/.npm-packages/bin:$PATH
  setup_script: npm install --global prettier@2.0.5
  check_script: make checkstyle-md

deploy_task:
  name: Build binaries and deploy to bintray
  only_if: $CIRRUS_PR == ""
  env:
    BINTRAY_TOKEN: ENCRYPTED[1a1820d17a2014de6b1798d379f86aa24bbd8acd5149656a98bfdf33746c78c85fefc8e6e522fedacdf8c4bf92bb25a0]
  go_modules_cache:
    fingerprint_script: cat go.sum
    folder: $GOPATH/pkg/mod
  container:
    image: theelves/cirrus-builder
  go_version_script: go version
  deploy_script: ./tools/cirrus-deploy.sh
