test_task:
  env:
    ELVISH_TEST_TIME_SCALE: 20
  go_toolchain_cache:
    fingerprint_key: go1.18
    folder: /usr/local/go
    populate_script: |
      pkg install -y curl
      curl -LO https://go.dev/dl/go1.18.freebsd-amd64.tar.gz
      tar -C /usr/local -xf go1.18.freebsd-amd64.tar.gz
  go_modules_cache:
    fingerprint_script: cat go.sum
    folder: $HOME/go/pkg/mod
  matrix:
    # Re-enable gccgo when it supports Go 1.18.
    #- name: Test on gccgo
    #  container:
    #    image: debian:unstable-slim
    #  setup_script:
    #    - apt-get -y update
    #    - apt-get -y install ca-certificates gccgo-11
    #    - ln -sf /usr/bin/go-11 /usr/local/bin/go
    - name: Test on FreeBSD
      freebsd_instance:
        image_family: freebsd-13-0
      env:
        PATH: /usr/local/go/bin:$HOME/go/bin:$PATH
      setup_script:
        - pkg install -y git
        - go install github.com/charmbracelet/glow@latest
  go_version_script: go version
  test_script: gmake test
