coverage:
  status:
    project:
      default:
        threshold: 0.1%
    patch: off
comment: false
ignore:
  # Exclude test helpers from coverage calculation.
  #
  # The following patterns are also consumed by a hacky sed script in tools/prune-cover.sh.
  - "pkg/cli/clitest"
  - "pkg/eval/evaltest"
  - "pkg/eval/vals/testutils.go"
  - "pkg/prog/progtest"
  - "pkg/store/storetest"
  - "pkg/testutil/must.go"
  # Exclude the copied rpc package.
  - "pkg/rpc"
  # The web UI is not being worked on now, also exclude it.
  - "pkg/web"
