// Command md2html converts Markdown to HTML.
//
// It is tailored for converting the Markdown sources of the Elvish website
// (https://elv.sh) to HTML. Based on [md.HTMLCodec], it adds the following
// generic features:
//
//   - Autogenerated ID for each heading
//
//   - Self link for each heading
//
//   - Generate a table of content (optional, turn on with <!-- toc -->)
//
//   - Generate section numbers for headings (optional, turn on with <--
//     number-sections -->)
//
// The comment block for optional features should appear before the main text,
// and can contain multiple features (like <!-- toc number-sections -->).
//
// It also adds the following Elvish-specific features:
//
//   - Syntax highlighting of code blocks with language elvish, elvish-bad and
//     elvish-transcript
//
// For general information about the Markdown implementation used by this
// command, see [src.elv.sh/pkg/md].
package main

import (
	"io"
	"log"
	"os"

	"src.elv.sh/pkg/md"
)

func main() {
	markdown, err := io.ReadAll(os.Stdin)
	if err != nil {
		log.Fatal(err)
	}
	codec := &htmlCodec{}
	codec.WriteCodeBlock = highlightCodeContent
	md.Render(string(markdown), md.SmartPunctsCodec{Inner: codec})
	os.Stdout.WriteString(codec.String())
}
