// Code generated by structoffunc; DO NOT EDIT.
//
//go:generate go run src.elv.sh/cmd/structoffunc -type=ListItems -output=zstructoffunc.go
package comps

import (
	etk "src.elv.sh/pkg/etk"
	ui "src.elv.sh/pkg/ui"
)

var _ ListItems = sofListItems{}
var _ = etk.RegisterStructOfFuncForInterface[sofListItems, ListItems]()

type sofListItems struct {
	LenImpl  func() int                      `elvish:"len"`
	GetImpl  func(int) any                   `elvish:"get"`
	ShowImpl func(int) (ui.Text, ui.Styling) `elvish:"show"`
}

func (sof sofListItems) Len() int {
	return sof.LenImpl()
}

func (sof sofListItems) Get(a1 int) any {
	return sof.GetImpl(a1)
}

func (sof sofListItems) Show(a1 int) (ui.Text, ui.Styling) {
	return sof.ShowImpl(a1)
}
