// Code generated by "stringer -type=fileFeature -output=ls-colors_string.go"; DO NOT EDIT.

package edit

import "fmt"

const _fileFeature_name = "featureInvalidfeatureOrphanedSymlinkfeatureSymlinkfeatureMultiHardLinkfeatureNamedPipefeatureSocketfeatureDoorfeatureBlockDevicefeatureCharDevicefeatureWorldWritableStickyDirectoryfeatureWorldWritableDirectoryfeatureStickyDirectoryfeatureDirectoryfeatureCapabilityfeatureSetuidfeatureSetgidfeatureExecutablefeatureRegular"

var _fileFeature_index = [...]uint16{0, 14, 36, 50, 70, 86, 99, 110, 128, 145, 180, 209, 231, 247, 264, 277, 290, 307, 321}

func (i fileFeature) String() string {
	if i < 0 || i >= fileFeature(len(_fileFeature_index)-1) {
		return fmt.Sprintf("fileFeature(%d)", i)
	}
	return _fileFeature_name[_fileFeature_index[i]:_fileFeature_index[i+1]]
}
