// Code generated by "stringer -type=TokenKind"; DO NOT EDIT

package edit

import "fmt"

const _TokenKind_name = "ParserErrorBarewordSingleQuotedDoubleQuotedVariableWildcardTildeSep"

var _TokenKind_index = [...]uint8{0, 11, 19, 31, 43, 51, 59, 64, 67}

func (i TokenKind) String() string {
	if i < 0 || i >= TokenKind(len(_TokenKind_index)-1) {
		return fmt.Sprintf("TokenKind(%d)", i)
	}
	return _TokenKind_name[_TokenKind_index[i]:_TokenKind_index[i+1]]
}
