// Code generated by "stringer -type=Reaction -output=zstring.go"; DO NOT EDIT.

package etk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unused-0]
	_ = x[Consumed-1]
	_ = x[Finish-2]
	_ = x[FinishEOF-3]
}

const _Reaction_name = "UnusedConsumedFinishFinishEOF"

var _Reaction_index = [...]uint8{0, 6, 14, 20, 29}

func (i Reaction) String() string {
	if i >= Reaction(len(_Reaction_index)-1) {
		return "Reaction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Reaction_name[_Reaction_index[i]:_Reaction_index[i+1]]
}
