#!/bin/sh -e

# To use this script as a Git hook:
#
#   cd .git/hooks # from repo root
#   ln -s ../../tools/pre-push .

if ! git diff-index --quiet HEAD; then
    echo 'Local changes exist.'
    echo 'Add those changes to the commit(s), stash them, or revert them.'
    echo
    git status
    exit 1
fi

# Verify the project is lint free and the tests pass. This simulates what is
# done in CI and we want to cause the checks to fail with a non-zero status.
export CI=yes
make lint
make test

# A quick cross-compilation test. Not exhaustive, but will catch most issues.
if test `go env GOOS` = windows; then
    GOOS=linux GOARCH=amd64 go build ./...
else
    GOOS=windows GOARCH=amd64 go build ./...
fi
